import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import MainNav from "./components/MainNav";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Transport Application",
  description: "Generated by KentWebs.com",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex flex-col m-3">
          <MainNav></MainNav>
        </nav>
        <main className="flex flex-col items-center bg-red-500">
          <div className="w-full max-w-6xl bg-white">{children}</div>
        </main>
      </body>
    </html>
  );
}
