import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import MainNav from "../components/MainNav";
import { ThemeProvider } from "../components/theme-provider";
import Logo from "../components/Logo";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Nayar",
  description: "Generated by KentWebs.com",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <nav className="flex flex-col m-1 border-b  mb-6 px-2 py-3">
            <div>
              <MainNav></MainNav>
            </div>
          </nav>

          <main className="flex flex-col items-center  ">
            <div className="w-full max-w-6xl  ">{children}</div>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
